/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ConstructionSite, Worker, AttendanceRecord, ExpenseRecord, ClientPayment } from './types';

export const INITIAL_SITES: ConstructionSite[] = [
  {
    id: 'site-1',
    name: 'Apex Commercial Plaza',
    location: '405 Industrial Parkway, Sector 4',
    supervisorName: 'Richard Vance',
    projectValue: 240000,
    budgetLimit: 180000,
    clientName: 'Apex Development Corp',
    clientPhone: '+1-555-0120',
    status: 'active',
    startDate: '2026-04-10',
    supervisorPasscode: '2222',
  },
  {
    id: 'site-2',
    name: 'Riverview Residential Villa',
    location: '12 Shoreline Boulevard',
    supervisorName: 'Arjun Mehta',
    projectValue: 135000,
    budgetLimit: 95000,
    clientName: 'Derrick & Sarah Johnson',
    clientPhone: '+1-555-0199',
    status: 'active',
    startDate: '2026-05-01',
    supervisorPasscode: '3333',
  },
  {
    id: 'site-3',
    name: 'Greenwood Highway Overpass',
    location: 'Bridge Sector 14, Route 9 North',
    supervisorName: 'Marcus Brodie',
    projectValue: 480000,
    budgetLimit: 390000,
    clientName: 'City Transit Authority',
    clientPhone: '+1-555-1122',
    status: 'active',
    startDate: '2026-03-01',
    supervisorPasscode: '4444',
  },
];

export const INITIAL_WORKERS: Worker[] = [
  { id: 'w-1', name: 'John Doe', role: 'Mason', dailyRate: 150, assignedSiteId: 'site-1', phone: '+1-555-4011', active: true },
  { id: 'w-2', name: 'Miguel Alvarez', role: 'Mason', dailyRate: 150, assignedSiteId: 'site-1', phone: '+1-555-4012', active: true },
  { id: 'w-3', name: 'David Lee', role: 'Carpenter', dailyRate: 160, assignedSiteId: 'site-1', phone: '+1-555-4013', active: true },
  { id: 'w-4', name: 'Samuel Jackson', role: 'Laborer', dailyRate: 100, assignedSiteId: 'site-1', phone: '+1-555-4014', active: true },
  { id: 'w-5', name: 'Vikram Singh', role: 'Laborer', dailyRate: 100, assignedSiteId: 'site-1', phone: '+1-555-4015', active: true },
  
  { id: 'w-6', name: 'Bobby Vance', role: 'Mason', dailyRate: 155, assignedSiteId: 'site-2', phone: '+1-555-3021', active: true },
  { id: 'w-7', name: 'Carlos Gomez', role: 'Laborer', dailyRate: 95, assignedSiteId: 'site-2', phone: '+1-555-3022', active: true },
  { id: 'w-8', name: 'Li Wei', role: 'Welder', dailyRate: 180, assignedSiteId: 'site-2', phone: '+1-555-3023', active: true },
  
  { id: 'w-9', name: 'James Carter', role: 'Operator', dailyRate: 200, assignedSiteId: 'site-3', phone: '+1-555-8091', active: true },
  { id: 'w-10', name: 'Luke Harrison', role: 'Mason', dailyRate: 160, assignedSiteId: 'site-3', phone: '+1-555-8092', active: true },
  { id: 'w-11', name: 'Anwar El-Amin', role: 'Laborer', dailyRate: 100, assignedSiteId: 'site-3', phone: '+1-555-8093', active: true },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // 3 days of attendance (May 22, 23, 24)
  // May 22
  { id: 'att-1', date: '2026-05-22', workerId: 'w-1', siteId: 'site-1', status: 'Present', wageEarned: 150 },
  { id: 'att-2', date: '2026-05-22', workerId: 'w-2', siteId: 'site-1', status: 'Present', wageEarned: 150 },
  { id: 'att-3', date: '2026-05-22', workerId: 'w-3', siteId: 'site-1', status: 'Half-Day', wageEarned: 80 },
  { id: 'att-4', date: '2026-05-22', workerId: 'w-4', siteId: 'site-1', status: 'Present', wageEarned: 100 },
  { id: 'att-5', date: '2026-05-22', workerId: 'w-5', siteId: 'site-1', status: 'Absent', wageEarned: 0 },
  { id: 'att-6', date: '2026-05-22', workerId: 'w-6', siteId: 'site-2', status: 'Present', wageEarned: 155 },
  { id: 'att-7', date: '2026-05-22', workerId: 'w-7', siteId: 'site-2', status: 'Present', wageEarned: 95 },
  { id: 'att-8', date: '2026-05-22', workerId: 'w-8', siteId: 'site-2', status: 'Present', wageEarned: 180 },
  { id: 'att-9', date: '2026-05-22', workerId: 'w-9', siteId: 'site-3', status: 'Present', wageEarned: 200 },
  { id: 'att-10', date: '2026-05-22', workerId: 'w-10', siteId: 'site-3', status: 'Present', wageEarned: 160 },
  { id: 'att-11', date: '2026-05-22', workerId: 'w-11', siteId: 'site-3', status: 'Half-Day', wageEarned: 50 },

  // May 23
  { id: 'att-12', date: '2026-05-23', workerId: 'w-1', siteId: 'site-1', status: 'Present', wageEarned: 150 },
  { id: 'att-13', date: '2026-05-23', workerId: 'w-2', siteId: 'site-1', status: 'Present', wageEarned: 150 },
  { id: 'att-14', date: '2026-05-23', workerId: 'w-3', siteId: 'site-1', status: 'Present', wageEarned: 160 },
  { id: 'att-15', date: '2026-05-23', workerId: 'w-4', siteId: 'site-1', status: 'Present', wageEarned: 100 },
  { id: 'att-16', date: '2026-05-23', workerId: 'w-5', siteId: 'site-1', status: 'Present', wageEarned: 100 },
  { id: 'att-17', date: '2026-05-23', workerId: 'w-6', siteId: 'site-2', status: 'Present', wageEarned: 155 },
  { id: 'att-18', date: '2026-05-23', workerId: 'w-7', siteId: 'site-2', status: 'Absent', wageEarned: 0 },
  { id: 'att-19', date: '2026-05-23', workerId: 'w-8', siteId: 'site-2', status: 'Present', wageEarned: 180 },
  { id: 'att-20', date: '2026-05-23', workerId: 'w-9', siteId: 'site-3', status: 'Present', wageEarned: 200 },
  { id: 'att-21', date: '2026-05-23', workerId: 'w-10', siteId: 'site-3', status: 'Present', wageEarned: 160 },
  { id: 'att-22', date: '2026-05-23', workerId: 'w-11', siteId: 'site-3', status: 'Present', wageEarned: 100 },

  // May 24
  { id: 'att-23', date: '2026-05-24', workerId: 'w-1', siteId: 'site-1', status: 'Present', wageEarned: 150 },
  { id: 'att-24', date: '2026-05-24', workerId: 'w-2', siteId: 'site-1', status: 'Half-Day', wageEarned: 75 },
  { id: 'att-25', date: '2026-05-24', workerId: 'w-3', siteId: 'site-1', status: 'Present', wageEarned: 160 },
  { id: 'att-26', date: '2026-05-24', workerId: 'w-4', siteId: 'site-1', status: 'Present', wageEarned: 100 },
  { id: 'att-27', date: '2026-05-24', workerId: 'w-5', siteId: 'site-1', status: 'Present', wageEarned: 100 },
  { id: 'att-28', date: '2026-05-24', workerId: 'w-6', siteId: 'site-2', status: 'Present', wageEarned: 155 },
  { id: 'att-29', date: '2026-05-24', workerId: 'w-7', siteId: 'site-2', status: 'Present', wageEarned: 95 },
  { id: 'att-30', date: '2026-05-24', workerId: 'w-8', siteId: 'site-2', status: 'Absent', wageEarned: 0 },
  { id: 'att-31', date: '2026-05-24', workerId: 'w-9', siteId: 'site-3', status: 'Present', wageEarned: 200 },
  { id: 'att-32', date: '2026-05-24', workerId: 'w-10', siteId: 'site-3', status: 'Present', wageEarned: 160 },
  { id: 'att-33', date: '2026-05-24', workerId: 'w-11', siteId: 'site-3', status: 'Present', wageEarned: 100 },
];

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: 'exp-1',
    date: '2026-05-21',
    siteId: 'site-1',
    supervisorName: 'Richard Vance',
    category: 'Fuel',
    description: 'Fuel for concrete mixing generator',
    amount: 120.50,
    paymentMethod: 'Supervisor Card',
    reimbursed: true,
  },
  {
    id: 'exp-2',
    date: '2026-05-22',
    siteId: 'site-1',
    supervisorName: 'Richard Vance',
    category: 'Tea & Meals',
    description: 'Mid-shift tea and refreshments for masonry crew',
    amount: 45.00,
    paymentMethod: 'Petty Cash',
    reimbursed: false,
  },
  {
    id: 'exp-3',
    date: '2026-05-23',
    siteId: 'site-2',
    supervisorName: 'Arjun Mehta',
    category: 'Urgent Material',
    description: 'Emergency extra anchor bolts from local store',
    amount: 210.00,
    paymentMethod: 'Supervisor Personal Out-of-pocket',
    reimbursed: false,
  },
  {
    id: 'exp-4',
    date: '2026-05-23',
    siteId: 'site-3',
    supervisorName: 'Marcus Brodie',
    category: 'Small Tools',
    description: 'Replacement grinder discs and masking tape',
    amount: 65.80,
    paymentMethod: 'Supervisor Card',
    reimbursed: true,
  },
  {
    id: 'exp-5',
    date: '2026-05-24',
    siteId: 'site-1',
    supervisorName: 'Richard Vance',
    category: 'Worker Advance',
    description: 'S. Jackson medical personal advance requested on shift',
    amount: 100.00,
    paymentMethod: 'Petty Cash',
    reimbursed: false,
  },
];

export const INITIAL_CLIENT_PAYMENTS: ClientPayment[] = [
  {
    id: 'pay-1',
    date: '2026-04-12',
    siteId: 'site-1',
    amount: 50000,
    paymentMethod: 'Bank Transfer',
    milestone: 'Project Kickoff Plan & Excavation Completion Approval',
    notes: 'Approved by Lead Architect',
    billingReference: 'BS-26-001',
    billingStage: 'Down Payment',
    status: 'Paid in Full',
    accomplishmentRate: 15,
    grossAmount: 50000,
  },
  {
    id: 'pay-2',
    date: '2026-05-18',
    siteId: 'site-1',
    amount: 72000,
    paymentMethod: 'Bank Transfer',
    milestone: 'Foundation Pour & Structural Beam Column Casting',
    notes: 'Verified by City Transit Authority Inspector',
    billingReference: 'BS-26-002',
    billingStage: 'Progress Billing',
    status: 'Paid in Full',
    accomplishmentRate: 30,
    grossAmount: 75000,
    withholdingRate: 4,
    withholdingAmount: 3000,
  },
  {
    id: 'pay-3',
    date: '2026-05-02',
    siteId: 'site-2',
    amount: 40000,
    paymentMethod: 'Cheque',
    milestone: 'Advance Deposit & Retaining Wall Start',
    notes: 'Initial mobilizations check received',
    billingReference: 'BS-26-003',
    billingStage: 'Down Payment',
    status: 'Paid in Full',
    accomplishmentRate: 20,
    grossAmount: 40000,
  },
  {
    id: 'pay-4',
    date: '2026-03-05',
    siteId: 'site-3',
    amount: 144000,
    paymentMethod: 'Bank Transfer',
    milestone: 'Design Submission & Road Grade Leveling Approval',
    notes: 'Cleared bank routing',
    billingReference: 'BS-26-004',
    billingStage: 'Progress Billing',
    status: 'Paid in Full',
    accomplishmentRate: 25,
    grossAmount: 150000,
    withholdingRate: 4,
    withholdingAmount: 6000,
  },
  {
    id: 'pay-5',
    date: '2026-05-24',
    siteId: 'site-2',
    amount: 25000,
    paymentMethod: 'Bank Transfer',
    milestone: 'Second Level Column Forms Construction',
    notes: 'Awaiting client executive panel clearance',
    billingReference: 'BS-26-005',
    billingStage: 'Progress Billing',
    status: 'Pending Approval',
    accomplishmentRate: 40,
    grossAmount: 25000,
  }
];
